version: "3.3"
services:
  service:
    container_name: "service"
    build: "./src"
    networks:
      - net
    ports:
      - "8080:8080"
    volumes:
      - "./src:/go/src/service"
    depends_on:
      - db

  web:
    container_name: "websrv-nginx"
    image: "nginx:latest"
    networks:
      - net
    ports:
      - "80:80"
    volumes:
      - "./view:/usr/share/nginx/html"
    depends_on:
      - "service"

  db:
    image: postgres:latest
    container_name: db
    hostname: db
    restart: "always"
    networks:
      - net
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dbasego
networks: net:
